'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarCheck, GraduationCap, LayoutDashboard, LogOut, Megaphone, RefreshCw, Users, BookOpen, ClipboardList } from 'lucide-react';
import { supabase } from '../lib/supabase';

type Data={teacher:any;assignments:any[];students:any[];attendance:any[];exams:any[];results:any[];announcements:any[]};
const today=()=>new Date().toISOString().slice(0,10);

export default function Page(){
 const [session,setSession]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{const s=supabase(); s.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:{subscription}}=s.auth.onAuthStateChange((_e,ss)=>setSession(ss)); return()=>subscription.unsubscribe()},[]);
 if(loading)return <div className="login"><div className="card loginCard">Loading NPSD Teacher Portal…</div></div>;
 return session?<Dashboard session={session}/>:<Login/>;
}
function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');const {error}=await supabase().auth.signInWithPassword({email,password});if(error)setError(error.message);setBusy(false)}
 return <div className="login"><form className="card loginCard" onSubmit={submit}><GraduationCap size={34}/><h1>NPSD Teacher Portal</h1><p className="muted">Secure teacher access</p><label className="label">Email<input className="input" type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="label">Password<input className="input" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="btn primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button>{error&&<div className="error">{error}</div>}</form></div>}
function Dashboard({session}:{session:any}){const [data,setData]=useState<Data|null>(null);const [tab,setTab]=useState('overview');const [error,setError]=useState('');const [refresh,setRefresh]=useState(false);
 async function load(){setRefresh(true);setError('');try{const r=await fetch('/api/teacher-data',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const p=await r.json();if(!r.ok)throw new Error(p.error||'Unable to load teacher data');setData(p)}catch(e:any){setError(e.message)}finally{setRefresh(false)}}
 useEffect(()=>{void load()},[]);
 if(!data)return <div className="login"><div className="card loginCard">{error?<><h2>Access unavailable</h2><div className="error">{error}</div><button className="btn primary" onClick={()=>void load()}>Retry</button></>: 'Loading dashboard…'}</div></div>;
 const nav=[['overview','Dashboard',LayoutDashboard],['students','Students',Users],['attendance','Attendance',CalendarCheck],['exams','Exams & Marks',ClipboardList],['results','Results',BookOpen],['announcements','Announcements',Megaphone]] as const;
 return <div className="shell"><aside className="side"><div className="brand">NPSD <span className="muted">Teacher</span></div><div className="muted">{data.teacher?.full_name||session.user.email}</div><nav className="nav">{nav.map(([id,label,Icon])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}><Icon size={17}/> {label}</button>)}</nav><div style={{marginTop:'auto'}}><button className="nav" style={{width:'100%'}} onClick={()=>void supabase().auth.signOut()}><span className="nav"><LogOut size={17}/> Sign out</span></button></div></aside><main className="main"><div className="top"><div><h1 style={{margin:'0 0 6px'}}>Good day, {data.teacher?.full_name||'Teacher'}</h1><div className="muted">Only assigned classes and students are available.</div></div><button className="btn" onClick={()=>void load()}><RefreshCw size={16}/> {refresh?'Refreshing…':'Refresh'}</button></div>{error&&<div className="error">{error}</div>}{tab==='overview'&&<Overview d={data}/>} {tab==='students'&&<Students d={data}/>} {tab==='attendance'&&<Attendance d={data} token={session.access_token} reload={load}/>} {tab==='exams'&&<Exams d={data}/>} {tab==='results'&&<Results d={data}/>} {tab==='announcements'&&<Announcements d={data}/>}</main></div>}
function Overview({d}:any){return <><div className="grid"><div className="card stat">Assigned classes<b>{d.assignments.length}</b></div><div className="card stat">Students<b>{d.students.length}</b></div><div className="card stat">Attendance records<b>{d.attendance.length}</b></div><div className="card stat">Results<b>{d.results.length}</b></div></div><section className="card section"><h2>My assignments</h2><div className="tableWrap"><table className="table"><thead><tr><th>Class</th><th>Subject</th></tr></thead><tbody>{d.assignments.map((a:any)=><tr key={a.id}><td>{a.classes?.name||'—'} {a.classes?.section?`— ${a.classes.section}`:''}</td><td>{a.subjects?.name||a.subject||'—'}</td></tr>)}</tbody></table></div></section></>}
function Students({d}:any){return <section className="card section"><h2>Assigned students</h2><div className="tableWrap"><table className="table"><thead><tr><th>Student ID</th><th>Name</th><th>Father</th><th>Class</th></tr></thead><tbody>{d.students.map((s:any)=><tr key={s.id}><td><span className="badge">{s.student_id}</span></td><td>{s.full_name}</td><td>{s.father_name||'—'}</td><td>{s.classes?.name||'—'} {s.classes?.section?`— ${s.classes.section}`:''}</td></tr>)}</tbody></table></div></section>}
function Attendance({d,token,reload}:any){const [date,setDate]=useState(today());const [status,setStatus]=useState<Record<string,string>>({});const [msg,setMsg]=useState('');async function save(){setMsg('');const rows=d.students.map((s:any)=>({student_id:s.id,attendance_date:date,status:status[s.id]||'present'}));const r=await fetch('/api/teacher-attendance',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({rows})});const p=await r.json();if(!r.ok)setMsg(p.error||'Save failed');else{setMsg('Attendance saved.');await reload()}}return <section className="card section"><div className="row"><h2 style={{marginRight:'auto'}}>Attendance</h2><input className="input" style={{width:170}} type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="btn primary" onClick={()=>void save()}>Save attendance</button></div>{msg&&<div className={msg.includes('saved')?'success':'error'}>{msg}</div>}<div className="tableWrap"><table className="table"><thead><tr><th>Student</th><th>Status</th></tr></thead><tbody>{d.students.map((s:any)=><tr key={s.id}><td>{s.student_id} — {s.full_name}</td><td><select className="select" value={status[s.id]||'present'} onChange={e=>setStatus({...status,[s.id]:e.target.value})}><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option><option value="leave">Leave</option></select></td></tr>)}</tbody></table></div></section>}
function Exams({d}:any){return <section className="card section"><h2>Exams</h2><div className="tableWrap"><table className="table"><thead><tr><th>Name</th><th>Date</th><th>Class</th><th>Published</th></tr></thead><tbody>{d.exams.map((e:any)=><tr key={e.id}><td>{e.name}</td><td>{e.exam_date||'—'}</td><td>{e.classes?.name||'—'}</td><td>{e.published?'Yes':'No'}</td></tr>)}</tbody></table></div></section>}
function Results({d}:any){return <section className="card section"><h2>Results</h2><div className="tableWrap"><table className="table"><thead><tr><th>Student</th><th>Subject</th><th>Marks</th><th>Grade</th></tr></thead><tbody>{d.results.map((r:any)=><tr key={r.id}><td>{r.students?.student_id||'—'}</td><td>{r.subject||'—'}</td><td>{r.marks_obtained??r.obtained??'—'} / {r.total_marks??r.total??'—'}</td><td>{r.grade||'—'}</td></tr>)}</tbody></table></div></section>}
function Announcements({d}:any){return <section className="card section"><h2>Announcements</h2>{d.announcements.map((a:any)=><article key={a.id} style={{padding:'14px 0',borderBottom:'1px solid #edf0f5'}}><b>{a.title}</b><p className="muted">{a.body||''}</p></article>)}</section>}
